### ISSUE TITLE
Cyrillic header length bug

### ISSUE THREAD

**Issue by ailjushkin** [tadashi-aikawa/markowl#1]
Greetings.

1. It seems that when header has cyrillic letters, its length is calculated with wrong method

```
| Файл коллекции | Файл задачи | Описание                               |
| --------------------------- | --------------------- | ---------------------------------------------- |
| tasks                       |                       | Директория invoke-коллекций |
```

but for english table it is normal after formatting

```
| asd asdas d | Asdas da s | ASDAS | 
| ----------- | ---------- | ----- | 
| a           | d          | d     | 

```

2, The plugin is not available in IntellijIdea, but it is extra needed there.

Please help me with it, because it seems that it is the first plugin only for formatting md tables and it's beautiful.

**Comment by tadashi-aikawa** [comment]
@ailjushkin 
Thank you for the bug report 😄 

> 2, The plugin is not available in IntellijIdea, but it is extra needed there.

Can you try to install it again?

Markowl (～ v0.5.0) had the evil compatibility and I fixed it yesterday as v0.5.2.
(After you created this issue, JetBrains approved it and publicly it.)

> 1. It seems that when header has cyrillic letters, its length is calculated with wrong method

I will challenge to fix this issue 👍 

Best regards.

**Comment by tadashi-aikawa** [comment]
http://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt

**Comment by ailjushkin** [comment]
Thank you, man!

**Comment by ailjushkin** [comment]
> 2. The plugin is not available in IntellijIdea, but it is extra needed there.

I appreciate it, plugin is now available in intellij idea

**Comment by tadashi-aikawa** [comment]
@ailjushkin 
I fixed the issue like the following gif.
![markowl_cyrillic](https://user-images.githubusercontent.com/9500018/88919932-ecf36680-d2a6-11ea-9e1b-5d0cc2715864.gif)

I will release a new version v0.6.0 from now on.
It would probably be tomorrow or day after tomorrow that you can upgrade it because JetBrains needs to approve it.

Best regards.

**Comment by tadashi-aikawa** [comment]
@ailjushkin 
Published! please try it 👍 
https://plugins.jetbrains.com/plugin/14116-markowl

**Comment by ailjushkin** [comment]
That's awesome, thank you, it's working!
