### ISSUE TITLE
Documentation on how to trigger the formatter with foreign keyboards

### ISSUE THREAD

**Issue by sod1497** [tadashi-aikawa/markowl#3]
I haven't been able to use the plugin because I can't perform the Alt + ; shortcut with the standard Spanish keyboard. It would be interesting showing how to configure the shortcuts that trigger the formatter.

**Comment by tadashi-aikawa** [comment]
@sod1497 
Thank you for your feedback 😄

I have written [FAQ](https://github.com/tadashi-aikawa/markowl#how-can-i-change-shortcut-keys-i-cant-or-dont-want-to-use-default-shortcut-keys) about changing shortcut keys 👍

**Comment by sod1497** [comment]
Thank you so much! 😊
